### ISSUE TITLE
Expand Spring support for Rspec & regular mode

### ISSUE THREAD

**Issue by mhmakshanoff** [KnapsackPro/knapsack_pro-ruby#110]
I saw a previous request for spring support to speed up executions, and that it had been implemented specifically for cucumber in queue mode: https://github.com/KnapsackPro/knapsack_pro-ruby/pull/98

Is it possible to expand support of this so that it can be utilized for Rspec in non-queue (regular) mode?

Happy to also fork and put up a PR myself

**Comment by ArturT** [comment]
Hey @mhmakshanoff 

I've just tested it and it's already possible to use [spring](https://github.com/rails/spring).

Please try: `bundle exec spring rake "knapsack_pro:rspec"` then you will see in output:

```
Running via Spring preloader in process 41166
```

In case of Cucumber I had to do this PR https://github.com/KnapsackPro/knapsack_pro-ruby/pull/98 because Cucumber was started via running `bundle exec cucumber` command via `Kernel.system` so I needed to pass spring prefix. 
https://knapsackpro.com/faq/question/how-to-use-spring-gem-to-run-cucumber-tests-faster-in-queue-mode

But in case of RSpec, I just run rake task https://github.com/KnapsackPro/knapsack_pro-ruby/blob/a2ae253/lib/knapsack_pro/runners/rspec_runner.rb#L22 so spring should already work if your add spring to knapsack command as I did in `bundle exec spring rake "knapsack_pro:rspec"`

I probably should add info about using spring with RSpec to my FAQ.

**Comment by ArturT** [comment]
I've added info to the FAQ how to use spring :)
https://knapsackpro.com/faq/question/how-to-use-spring-gem-with-knapsack-pro

Let me know if this works for you. Thanks.

**Comment by Hanaffi** [comment]
@ArturT, I wonder how you managed to get Spring working on CI, please.
I'm getting this error:

```rb
'Spring::Client::Run#verify_server_version': Error connecting to Spring server (RuntimeError)
```
