### ISSUE TITLE
Is this free?

### ISSUE THREAD

**Issue by thedrow** [KnapsackPro/knapsack_pro-ruby#13]
Pro usually indicates paid. It's worthwhile to clear this out in the README.

**Comment by thedrow** [comment]
Also, will this be always free for open source?

**Comment by ArturT** [comment]
knapsack_pro gem is open source but relies on closed Knapsack Pro API.  I'd like to get feedback from people trying knapsack pro for free and I'd like to work closely with them to validate if the solution I'm building provide a value for the users. Switching to paid plan is a good way to validate that and a way to get support from happy users. 

Currently, there is no hard limit when the free trial is ending. I'm more interested in getting feedback from users in order to improve the tool. As I saw in the past people want to support the project and are asking for paid plan. 

> Also, will this be always free for open source?

Good question. This might be a good idea to keep Knapsack Pro free for open source projects. Maybe thanks to that knapsack pro can be promoted. The owner of the open source project could add the link to Knapsack Pro website in the readme as a way to say thanks. 

Do you have any open source project where you would like to use knapsack_pro? I'm happy to help.

**Comment by thedrow** [comment]
We're looking into it for the company I work for.
But if it will be free for open source projects I can recommend it to other people.

**Comment by ArturT** [comment]
I updated the readme https://github.com/KnapsackPro/knapsack_pro-ruby#is-knapsack_pro-gem-free
It's free for open source. 

Thanks for the good question. Feel free to contact me via email when you need help with the set up of the gem.
