### ISSUE TITLE
All examples skipped after exception in before: suite hook in queue mode

### ISSUE THREAD

**Issue by amanfredi** [KnapsackPro/knapsack_pro-ruby#196]
We run 40 parallel CI runners using knapsack pro queue mode, which normally complete in about 10 minutes each.
I recently observed that after retrying certain failed test nodes, the test runner would consistently time out. I realized this was because the runner had fetched more tests from the knapsack queue than it could possibly execute, and that distribution was persisted with the fixed queue split & retry configuration. The underlying cause of this is that the first failure did not fail the entire run, but instead caused knapsack to continue fetching examples from the queue and then not actually execute them.

See the following log for examples:

```
I, [2023-05-19T16:35:06.300147 #129]  INFO -- : [knapsack_pro] To retry the last batch of tests fetched from the API Queue, please run the following command on your machine:
I, [2023-05-19T16:35:06.300239 #129]  INFO -- : [knapsack_pro] bundle exec rspec --profile=5 --format documentation --color --format RspecJunitFormatter --out tmp/rspec.xml --default-path spec <<<spec-files-batch-1>>>"

An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean

ActiveRecord::ConnectionTimeoutError:
  could not obtain a connection from the pool within 5.000 seconds (waited 5.005 seconds); all pooled connections were in use
<<<stacktrace>>>

I, [2023-05-19T16:35:11.656783 #129]  INFO -- : [knapsack_pro] To retry the last batch of tests fetched from the API Queue, please run the following command on your machine:
I, [2023-05-19T16:35:11.656859 #129]  INFO -- : [knapsack_pro] bundle exec rspec --profile=5 --format documentation --color --format RspecJunitFormatter --out tmp/rspec.xml --default-path spec <<<spec-files-batch-2>
No examples found.

I, [2023-05-19T16:35:11.949911 #129]  INFO -- : [knapsack_pro] To retry the last batch of tests fetched from the API Queue, please run the following command on your machine:
I, [2023-05-19T16:35:11.949998 #129]  INFO -- : [knapsack_pro] bundle exec rspec --profile=5 --format documentation --color --format RspecJunitFormatter --out tmp/rspec.xml --default-path spec <<<spec-files-batch-3>>>
No examples found.

...
```

**Comment by ArturT** [comment]
Hi @amanfredi 

I'm wondering how to reproduce it. I did 

```ruby
# spec_helper.rb
KnapsackPro::Hooks::Queue.before_queue do |queue_id|
  raise 'a'
end
```

Indeed knapsack pro consumes tests from Queue API and does it fast. It does not execute tests because RSpec could not start tests due to a failure. Tests failed.

CI build should complete work faster when tests are not executed.

I'm not sure why you experienced a timeout from CI? Do you mean you fixed the bug in the code and you started a new build (attempted some kind of retry) and it was split using cached distribution (fixed queue split) so that a single CI node got too many tests (due to them being cached on the API side). If you fixed a bug in the code then I would expect a new git commit hash so that the fixed queue split (cached distribution on API side) won't be used.

Could you give more details on how to reproduce the problem. What you did?
Did you start 1 CI build or maybe 2 because you did a retry? Did you create a new commit?
What would you expect to happen?
