### ISSUE TITLE
Queue Mode Retry

### ISSUE THREAD

**Issue by sj26** [KnapsackPro/knapsack_pro-ruby#21]
Queue mode is awesome. Being able to distribute a test suite in real time so that nodes finish in roughly equal time is amazing.

We've had one small snag. Running a big integration test suite is bound to result in flakey test failures. On Buildkite we run our rspec integration tests in parallel, so there are many jobs all running a piece of the suite concurrently. Turning on queue mode works great, and results in a very speedy test run. But if one of those parallel jobs has a failure, when it finishes we can re-run just that particular job to retry just that piece of the test suite. Some of the other jobs might still be running. But re-running that same job, with the same rspec seed, doesn't run the same tests.

Is there some way to make sure that re-running the same node in a particular build in queue mode runs the same piece of the test suite again, if it has completed once before?

**Comment by sj26** [comment]
If it helps, we expose whether the current job is a retry with an environment variable: `$BUILDKITE_RETRY_COUNT`.

**Comment by sj26** [comment]
For a particular case, the first time this job ran the first knapsack API request was:

```
I, [2017-01-16T05:42:43.480208 #56]  INFO -- : [knapsack_pro] API request UUID: ad067d1c-dd76-468d-a82b-ecf706ebd8ca

I, [2017-01-16T05:42:43.480295 #56]  INFO -- : [knapsack_pro] API response:

I, [2017-01-16T05:42:43.480355 #56]  INFO -- : [knapsack_pro] {"queue_name"=>"4:a027814bab3330a4c44570a4100f2275", "test_files"=>[{"path"=>"spec/features/editing_user_settings_spec.rb", "time_execution"=>87.95692682266235}]}
```

On the job retry, the second run, the first API request was:

```
I, [2017-01-16T07:52:30.124136 #59]  INFO -- : [knapsack_pro] API request UUID: 6d0c7728-89d8-4c14-b391-84411f2968c3
I, [2017-01-16T07:52:30.124209 #59]  INFO -- : [knapsack_pro] API response:
I, [2017-01-16T07:52:30.124297 #59]  INFO -- : [knapsack_pro] {"queue_name"=>"4:a027814bab3330a4c44570a4100f2275", "test_files"=>[{"path"=>"spec/features/escalate_session_spec.rb", "time_execution"=>145.04361748695374}]}
```

(Hopefully those details don't contain secrets!)

**Comment by ArturT** [comment]
> But if one of those parallel jobs has a failure, when it finishes we can re-run just that particular job to retry just that piece of the test suite. 

Why you retry this single CI node with failed tests? Do you have tests that gives you random fail and you are hoping to rerun them just to make build pass?

Why don't you re run whole build or commit a fix for tests and run a new build? I'm trying to find and understand the root problem/reason in your case.

In theory re runing the same build would take the same amount of time as running just single CI node. Maybe you want to run just single failed CI node to save power of other CI nodes so they can be used for other builds at the same time?


Currently when single CI node finishes (in your cases it finished with some failed tests) and other CI nodes are still running. When you retry single CI node it will connect to the existing queue as you can see in knapsack log:

```
"queue_name"=>"4:a027814bab3330a4c44570a4100f2275"
```
It means the retried CI node will run some of test files from the ending queue.

In case when all CI nodes finished (the queue is empty on API side) and you will retry single CI node then it will initialize a new queue on API side and that would mean that the single CI node is only running against this queue so it will run your whole test suite on this single CI node.

When you do rerun of CI node is BUILDKITE_BUILD_NUMBER still the same?

I'm wondering about solution for this problem of reruning single CI node.
In regular knapsack pro mode it was done with KNAPSACK_PRO_FIXED_TEST_SUITE_SPLIT=true (default)
https://github.com/KnapsackPro/knapsack_pro-ruby#knapsack_pro_fixed_test_suite_splite-test-suite-split-based-on-seed

In case of queue mode I would have to remember what test files were fetched from the single CI node so when you would do rerun for single CI node with the same build ID (BUILDKITE_BUILD_NUMBER) then the single CI node should get exactly the same test files.

In case when you will rerun whole build (all CI nodes) for the same git commit then we should do again dynamic allocation of test files to avoid edge case when the first build for particular commit is dynamically allocated but the second build (for instance whole build retry for the same git commit) ends up with not dynamic allocation because of remembered test files per CI node (unless whole build retry means there is a new BUILDKITE_BUILD_NUMBER ).

There is one more edge case to consider. With queue mode the CI node asks knapsack pro API a few times for list of test files so basically it looks like this:
```
CI node asks API and runs a_spec.rb b_spec.rb (this has seed 1)
CI node asks API and runs c_spec.rb (this has seed 2)
```
When we would do rerun of CI node then we would run all test files at once (or we would have to store on API side info what and how many list of tests were fetched from the queue for that particular CI node):
```
CI node runs a_spec.rb b_spec.rb c_spec.rb 
```
instead of splitting it into 2 runs.


If you want to run tests with the same seed you must do it on local machine and provide seed.
In regular mode you must do it locally too. Reruning with regular mode doesn't remember seed.


I need to think more about it and what would be reasonable option to solve this problem and whether this problem should be solved at all.

Is this like must have feature in your context?

**Comment by ArturT** [comment]
@sj26 Hey, I've just released a new gem version that solves this issue.

Please set `KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true` so when you retry CI node then it will use previously executed test files.

You can learn more about it here:
https://github.com/KnapsackPro/knapsack_pro-ruby#knapsack_pro_fixed_queue_split-remember-queue-split-on-retry-ci-node
