### ISSUE TITLE
Hooks for queue mode start/finish

### ISSUE THREAD

**Issue by chendo** [KnapsackPro/knapsack_pro-ruby#28]
We're using Percy.io for our visual regression testing, and they depend on `before(:suite)` and `after(:suite)` hooks to notify their backend when a build starts and completes by counting the number of begin and finalise calls that match the total node count. However, the suite hooks fire between queue chunk runs. Is there hooks that let me have these hooks only be run once per node?

**Comment by ArturT** [comment]
At this moment knapsack_pro has no hook like that and probably it might be a bit hard to provide `after queue end hook` because I know when queue is ended when I got no test files from Knapsack Pro API. It means I won't run more tests to hook into `after(:suite)` to set the knapsack pro `after queue end hook`.
Maybe I could find other workaround but I need to think more about it.

I looked at the documentation https://percy.io/docs/clients/ruby/capybara-rails
and probably this may work. 

```ruby
# spec_helper.rb or rails_helper.rb
unless ENV['KNAPSACK_PRO_RSPEC_PERCY_HOOKS_LOADED']
  ENV['KNAPSACK_PRO_RSPEC_PERCY_HOOKS_LOADED'] = 'true'
  Percy::Capybara.initialize_build
  at_exit { Percy::Capybara.finalize_build }
end
```
Could you check that?

**Comment by chendo** [comment]
Seems to work, thanks!

**Comment by ArturT** [comment]
Great! I've updated FAQ https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-set-beforesuite-and-aftersuite-rspec-hooks-in-queue-mode-percyio-example

**Comment by ArturT** [comment]
I think the example can be even more simplified:

```ruby
# spec_helper.rb or rails_helper.rb

# executes before Queue Mode starts work
Percy::Capybara.initialize_build

# executes after Queue Mode finishes work
at_exit { Percy::Capybara.finalize_build }
```

I tested that and this should be executed only once at the beginning and at the end.
